-- Configure roles/user
use role useradmin;
create or replace role semi_structured_demo;
GRANT ROLE SEMI_STRUCTURED_DEMO TO ROLE SYSADMIN;
grant role semi_structured_demo to user johnlasater2;

-- Setup database 
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE SEMI_STRUCTURED_DEMO;
GRANT OWNERSHIP ON DATABASE SEMI_STRUCTURED_DEMO TO ROLE SEMI_STRUCTURED_DEMO;
USE ROLE SEMI_STRUCTURED_DEMO;
CREATE SCHEMA SEMI_STRUCTURED_DEMO.STG;


SHOW GRANTS ON DATABASE SNOWFLAKE_SAMPLE_DATA;